/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef ESPMIDI_VERSION_H
#define ESPMIDI_VERSION_H

#define ESPMIDI_VERSION_MAJOR 0
#define ESPMIDI_VERSION_MINOR 1
#define ESPMIDI_VERSION_PATCH 0
#define ESPMIDI_VERSION_STR "0.1.0"

#endif // ESPMIDI_VERSION_H
